### ISSUE TITLE
nextjs使用报错`TypeError: (0 , _react.useRef) is not a function`

### ISSUE THREAD

**Issue by xmsz** [alibaba/hooks#2214]
```
- error node_modules/.pnpm/ahooks@3.7.7_react@18.2.0/node_modules/ahooks/lib/useLatest/index.js (9:31) @ value
- error TypeError: (0 , _react.useRef) is not a function
    at Home (./src/app/page.tsx:16:66)
    at stringify (<anonymous>)
null
- error node_modules/.pnpm/ahooks@3.7.7_react@18.2.0/node_modules/ahooks/lib/useLatest/index.js (9:31) @ value
- error TypeError: (0 , _react.useRef) is not a function
    at Home (./src/app/page.tsx:16:66)
    at stringify (<anonymous>)
digest: "4049301014"
null
- wait compiling /favicon.ico/route (client and server)...
- event compiled client and server successfully in 718 ms (1085 modules)
- warn Fast Refresh had to perform a full reload due to a runtime error.
- error node_modules/.pnpm/ahooks@3.7.7_react@18.2.0/node_modules/ahooks/lib/useLatest/index.js (9:31) @ value
- error TypeError: (0 , _react.useRef) is not a function
    at Home (./src/app/page.tsx:16:66)
    at stringify (<anonymous>)
null
- error node_modules/.pnpm/ahooks@3.7.7_react@18.2.0/node_modules/ahooks/lib/useLatest/index.js (9:31) @ value
- error TypeError: (0 , _react.useRef) is not a function
    at Home (./src/app/page.tsx:16:66)
    at stringify (<anonymous>)
digest: "4049301014"
null

```

**Comment by liuyib** [comment]
能否提供个可复现的在线 demo 链接？ codepen, codesandbox 这种 @xmsz
