### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by HT-Moh** [alibaba/hooks#2254]
I did update few packages recently then I start having the following error

```
unhandledRejection /src/profiler/nextjs/node_modules/ahooks/es/useAsyncEffect/index.js:1
import { __awaiter, __generator } from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 59162 (/home/bicatalyst/src/profiler/nextjs/.next/server/pages/_document.js:120:18)
    at __webpack_require__ (/home/bicatalyst/src/profiler/nextjs/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am using : 

"next": "^13.4.9",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"ahooks": "^3.7.8",

"eslint": "^8.43.0",
"@types/node": "^20.4.1",
"prettier": "^2.8.8",
"ts-node": "^10.9.1",
"typescript": "^5.1.6"

tsconfig.json
```json
{
  "compilerOptions": {
    "importHelpers": false,
    "target": "esnext" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */,
    "module": "esnext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
    "types": [
      "node",
      "jest"
    ],
    "lib": [
      /* Specify library files to be included in the compilation. */
      "es6",
      "es7",
      "esnext",
      "dom",
      "dom.iterable"
    ],
    "allowJs": true,
    "alwaysStrict": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve", /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "baseUrl": ".", /* Base directory to resolve non-absolute module names. */
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "incremental": true,
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
  },
  "exclude": [
    "node_modules",
    "tailwind.config.js",
    "**/*.test.*",
    "**/__mocks__/*",
    "**/__tests__/*",
    ".vscode",
    ".swc",
    ".next"
  ],
  "include": ["next-env.d.ts", ".d.ts", "**/*.ts", "**/*.tsx"]
}
```

**Comment by liuyib** [comment]
Is v3.7.7 normal? @HT-Moh

**Comment by HT-Moh** [comment]
I just change to version v3.77 same issue. 
I removed `useAsyncEffect` now I am getting the error for useToggle

[0]useToggle/index.js:1
[0] import { __read } from "tslib";
[0] ^^^^^^

**Comment by liuyib** [comment]
which bundler are you using？webpack? vite?

**Comment by HT-Moh** [comment]
As I mentioned before I am using "next": "^13.4.9",

**Comment by liuyib** [comment]
Has ahooks ever worked well in your project? Is this your first time using it?

**Comment by HT-Moh** [comment]
No it's not the first time, I am using it in my project for more than a year as well in production. 
Now it's working because I rollback the packages updates

![image](https://github.com/alibaba/hooks/assets/34759569/ee00c4ca-1a6a-4e52-a7cc-7e32316a4d01)

**Comment by liuyib** [comment]
Ok, I will trace the issue, thx @HT-Moh

**Comment by liuyib** [comment]
I use `npx create-next-app@latest` to create a new Next.js project, and install ahooks@^3.7.8, it works ok.

package.json:
```json
{
  "name": "test-next.js",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.4.1",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "ahooks": "^3.7.8",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.9",
    "next": "13.4.9",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.1.6"
  }
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

So, can you provide an online demo to reproduce this problem? thx @HT-Moh

**Comment by zhuiye** [comment]
meet the same question .

```
import useRequest from './src/useRequest';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

i use pnpm install in nextjs 

package.json

```json
   "@ant-design/icons": "5.1.0",
        "@ant-design/cssinjs": "^1.3.0",
        "@ant-design/static-style-extract": "~1.0.1",
        "react-hook-form": "^7.43.9",
        "antd": "^5.1.0",
        "cross-env": "^7.0.3",
        "eslint": "^8.30.0",
        "eslint-config-next": "^13.1.1",
        "next": "13.4.9",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "ts-node": "^10.9.1",
        "tslib": "^2.5.0",
        "typescript": "^4.9.4",
        "umi-request": "^1.3.9",
        "ahooks": "^3.7.8",
        "moment": "2.29.4"
```

**Comment by liuyib** [comment]
Who can provide an online demo, like this: https://codesandbox.io/p/sandbox/vigorous-dust-9cjmw2, to reproduce this problem? thx
@HT-Moh @zhuiye

**Comment by zhuiye** [comment]
@liuyib  hello  i make a demo.   https://github.com/zhuiye/nextjs_ahook     ,you can try it

**Comment by liuyib** [comment]
> @liuyib hello i make a demo. https://github.com/zhuiye/nextjs_ahook ,you can try it

Thx for your demo, I got this error!

You can solve it in the following way:

next.config.js:
```js
const nextConfig = {
  transpilePackages: ['ahooks']
};
```

**Comment by liuyib** [comment]
This is not ahooks related issue, try to solve it from nextjs or build tools.

I think this error has been solved, it's closed now, feel free to open a new issue if the problem still exist.

**Comment by meteorlxy** [comment]
I meet the same problem, and got another error in dev mode after adding `transpilePackages: ['ahooks']` [as suggested](https://github.com/alibaba/hooks/issues/2254#issuecomment-1630992225).

```sh
Module parse failed: Cannot use 'import.meta' outside a module (59:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or
```

According to the related PR https://github.com/vercel/next.js/pull/52031, fixed by:
- Remove `ahooks` from `modularizeImports`, or
- Update `'ahooks/es/{{member}}'` to `'ahooks/lib/{{member}}'`
