### ISSUE TITLE
Must use import to load ES Module: /root/workspace/pro-m/node_modules/lodash-es/lodash.js

### ISSUE THREAD

**Issue by JiaLuo** [alibaba/hooks#2456]
[16:29:24]  require() of ES modules is not supported.
[16:29:24] require() of /root/workspace/pro-m/node_modules/lodash-es/lodash.js from /root/workspace/pro-m/node_modules/ahooks/lib/useRequest/src/plugins/useDebouncePlugin.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[16:29:24] Instead rename lodash.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/workspace/pro-m/node_modules/lodash-es/package.json.
[16:29:24] 
[16:29:24]     at new NodeError (internal/errors.js:322:7)
[16:29:24]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
[16:29:24]     at Module.load (internal/modules/cjs/loader.js:950:32)
[16:29:24]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[16:29:24]     at Module.require (internal/modules/cjs/loader.js:974:19)
[16:29:24]     at require (internal/modules/cjs/helpers.js:101:18)
[16:29:24]     at Object.<anonymous> (/root/workspace/pro-m/node_modules/ahooks/lib/useRequest/src/plugins/useDebouncePlugin.js:8:17)
[16:29:24]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[16:29:24]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[16:29:24]     at Module.load (internal/modules/cjs/loader.js:950:32) {
[16:29:24]   code: 'ERR_REQUIRE_ESM'
[16:29:24] }
[16:29:24] 
[16:29:24] > Build error occurred
[16:29:24] Error: Failed to collect page data for /Activity/experience
[16:29:24]     at /root/workspace/pro-m/node_modules/next/dist/build/utils.js:916:15 {
[16:29:24]   type: 'Error'
[16:29:24] }

How to solve the above problems？

The code has not been touched for two months, and the result is that this problem occurs when the code is compiled again today

**Comment by lichenglong-blog** [comment]
你绝对3.7.8 提升到了3.7.9，没有锁版本

**Comment by peluprvi** [comment]
For me it looks like a breaking change or regression introduced on version v3.7.9.
I'm using the `useDebounceEffect` hook.

Edit:
[Comparing v3.7.8 to v3.7.9](https://github.com/alibaba/hooks/compare/v3.7.8...v3.7.9), I think the issue is related to the changes from `loadash` to `loadash-es`. Some possible related commits are  https://github.com/alibaba/hooks/commit/be1e14155f6eae38aad9e1e41a7846a8335f3a8f , https://github.com/alibaba/hooks/commit/a6313e9d398d621d92e65c2b617e2baf72f7d410 , https://github.com/alibaba/hooks/commit/4d9b9236f92ddb47fd0c6878adb0e858c6c0ab9d , https://github.com/alibaba/hooks/commit/7843f0229379272746d3c3faab77b534186bc583

Some changes have reverted: https://github.com/alibaba/hooks/pull/2453.

**Comment by JiaLuo** [comment]
> For me it looks like a breaking change or regression introduced on version v3.7.9. I'm using the `useDebounceEffect` hook.
> 
> Edit: [Comparing v3.7.8 to v3.7.9](https://github.com/alibaba/hooks/compare/v3.7.8...v3.7.9), I think the issue is related to the changes from `loadash` to `loadash-es`. Some possible related commits are [be1e141](https://github.com/alibaba/hooks/commit/be1e14155f6eae38aad9e1e41a7846a8335f3a8f) , [a6313e9](https://github.com/alibaba/hooks/commit/a6313e9d398d621d92e65c2b617e2baf72f7d410) , [4d9b923](https://github.com/alibaba/hooks/commit/4d9b9236f92ddb47fd0c6878adb0e858c6c0ab9d) , [7843f02](https://github.com/alibaba/hooks/commit/7843f0229379272746d3c3faab77b534186bc583)
> 
> Some changes have reverted: #2453.

I'm using version 3.1.3 and not the latest version

**Comment by JiaLuo** [comment]
> 你绝对3.7.8 提升到了3.7.9，没有锁版本

我没用最新版本，项目很早就创建了，当时下载的版本后面就一直没有更新过。昨天开始就突然编译不通过了

**Comment by chenggj** [comment]
I used the latest version 3.7.9, and have the same issue.
My lodash-es version is 4.17.21

**Comment by JiaLuo** [comment]
I locked the 3.1.3 version and the project is ready to compile

**Comment by chenggj** [comment]
I revert ahooks version to 3.7.8, and it builds success.

**Comment by best666** [comment]
使用了antd-mobile，里面依赖了ahooks没有锁版本，需要再package.json中加入：
```
"resolutions": {
    "ahooks": "3.7.8"
  }
```
顺带说一句，npm打包没有报错，换成yarn后有错误

**Comment by liuyib** [comment]
lodash-es 已回退到 lodash，目前 v3.7.10 已发版，各位可以升级下，如果还有问题的话，请随时反馈，感谢。
