### ISSUE TITLE
Error: 'CombineService' is not exported by node_modules/@umijs/use-request/lib/types.js

### ISSUE THREAD

**Issue by milobluebell** [alibaba/hooks#326]
你好，在自己写的脚手架里使用，有如下报错：

![image](https://user-images.githubusercontent.com/11535146/78003803-cf030d00-736b-11ea-8b69-3656333976e9.png)

```js
[16:13:12] 'bundle:asset:ts' errored after 11 s
[16:13:12] Error: 'CombineService' is not exported by node_modules/@umijs/use-request/lib/types.js, imported by node_modules/@umijs/hooks/es/useFormTable/index.js
    at error (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at Module.getVariableForExportName (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9969:25)
    at dependencies.concat.getReexports.concat.map (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9941:39)
    at Array.map (<anonymous>)
    at Module.getTransitiveDependencies (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9941:14)
    at Chunk$1.link (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:10985:48)
    at Promise.all.then (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:13343:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{ Error: 'CombineService' is not exported by node_modules/@umijs/use-request/lib/types.js, imported by node_modules/@umijs/hooks/es/useFormTable/index.js
    at error (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at handleMissingExport (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9725:28)
    at Module.traceVariable (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:10163:24)
    at Module.getVariableForExportName (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9969:25)
    at dependencies.concat.getReexports.concat.map (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9941:39)
    at Array.map (<anonymous>)
    at Module.getTransitiveDependencies (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:9941:14)
    at Chunk$1.link (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:10985:48)
    at Promise.all.then (/Users/milobluebell/Documents/newCashier/node_modules/rollup/dist/shared/node-entry.js:13343:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
pkg version:  `"@umijs/hooks": "^1.8.1"`
os:       mac catalina
node:  10.16.3
lan:      `preact`（但是目测和preact没关系吧？）

**Comment by milobluebell** [comment]
看了下对应的文件的确是空的

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/78038350-54ec7b80-739f-11ea-8320-4814c3f7817d.png)


我这边测试一切正常。
是不是你的 ts 版本太低了？或者可以给个在线复现什么的。

**Comment by milobluebell** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/78038350-54ec7b80-739f-11ea-8320-4814c3f7817d.png)
> 
> 我这边测试一切正常。
> 是不是你的 ts 版本太低了？或者可以给个在线复现什么的。

ts 3.8.3...

**Comment by milobluebell** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/78038350-54ec7b80-739f-11ea-8320-4814c3f7817d.png)
> 
> 我这边测试一切正常。
> 是不是你的 ts 版本太低了？或者可以给个在线复现什么的。

我晚点fork下来看一下吧

**Comment by brickspert** [comment]
你是用的 rollup 吗？可以看下这个 issue: https://github.com/rollup/plugins/issues/71

**Comment by guguji5** [comment]
我脚手架是Vite，build时候用的rollup。导致一些development下正常的包，比如`"@umijs/hooks": "^1.2.0"` 构建时候报错，有没有一些办法处理呢？
![image](https://user-images.githubusercontent.com/17986248/135066626-babd5652-d7e8-43aa-af33-52ecea5e4c70.png)

**Comment by brickspert** [comment]
> 我脚手架是Vite，build时候用的rollup。导致一些development下正常的包，比如`"@umijs/hooks": "^1.2.0"` 构建时候报错，有没有一些办法处理呢？

升级到 1.9.1 试试，https://github.com/alibaba/hooks/pull/343/files

**Comment by cool-518** [comment]
一样的问题，老哥你怎么解决的

**Comment by guguji5** [comment]
@cool-518 如果我没理解错。@umijs/hooks 被废弃了，似乎换成ahooks了。 try it
