### ISSUE TITLE
Incorrect Type Conversion in useDebounceFn & useThrottleFn

### ISSUE THREAD

**Issue by linbudu599** [alibaba/hooks#692]
构建过程中的错误：
![](https://juejin-article-img.oss-cn-hangzhou.aliyuncs.com/image_20201022190440.png)
代码：
```typescript
function useDebounceFn<T extends Fn>(fn: T, options?: DebounceOptions) {
  const fnRef = useRef<T>(fn);
  fnRef.current = fn;

  const wait = options?.wait ?? 1000;

  const debounced = useCreation(
    () =>
      debounce<T>(
        ((...args: any[]) => {
          return fnRef.current(...args);
        }) as T,
        wait,
        options,
      ),
    [],
  );

  return {
    run: debounced as T,
    cancel: debounced.cancel,
    flush: debounced.flush,
  };
}
```

最后的 `as T` 是错误且不必要的，`debounced` 已经是也应该是 `DebouncedFunc<T>`（这个类型别名来自于Lodash），从语义化角度来说，`run`函数是经过防抖处理的函数，所以更没啥问题。
这个问题同样存在于`useThrottleFn`中。
@brickspert @awmleer 需要我开个PR还是你们下次顺便修掉~

**Comment by brickspert** [comment]
不写 `as T` 是会报错的，见昨天的 issue ：https://github.com/alibaba/hooks/issues/690

**Comment by linbudu599** [comment]
有点奇怪,我在mac和win上都遇到了这个错误

**Comment by brickspert** [comment]
要不你试试 `as unknow as T` ？如果没有报错的话，可以来个 PR。

**Comment by awmleer** [comment]
@linbudu599 可以发一下你项目中的 `tsconfig.json` 么

**Comment by linbudu599** [comment]
> @linbudu599 可以发一下你项目中的 `tsconfig.json` 么

不是我项目中的问题，是`hooks`这个仓库我在`lerna run build`的时候报的错，完整的信息：

```shell
[11:36:29] Using gulpfile ~/Downloads/hooks-master/packages/hooks/gulpfile.js
[11:36:29] Starting 'default'...
[11:36:29] Starting 'clean'...
[11:36:29] Finished 'clean' after 15 ms
[11:36:29] Starting 'cjs'...
src/useDebounceFn/index.ts(27,10): error TS2352: Conversion of type 'DebouncedFunc<T>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'DebouncedFunc<T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Fn'.
src/useThrottleFn/index.ts(27,10): error TS2352: Conversion of type 'DebouncedFunc<T>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'DebouncedFunc<T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Fn'.
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)

    at /Users/qiongxin/Downloads/hooks-master/node_modules/_execa@0.8.0@execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  killed: false,
  stdout: '\n' +
    '> ahooks@2.7.1 build /Users/qiongxin/Downloads/hooks-master/packages/hooks\n' +
    '> gulp && webpack-cli\n' +
    '\n' +
    '[11:36:29] Using gulpfile ~/Downloads/hooks-master/packages/hooks/gulpfile.js\n' +
    "[11:36:29] Starting 'default'...\n" +
    "[11:36:29] Starting 'clean'...\n" +
    "[11:36:29] Finished 'clean' after 15 ms\n" +
    "[11:36:29] Starting 'cjs'...\n" +
    "\x1B[31msrc/useDebounceFn/index.ts(27,10): \x1B[39merror TS2352: Conversion of type 'DebouncedFunc<T>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.\n" +
    "  'DebouncedFunc<T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Fn'.\n" +
    "\x1B[31msrc/useThrottleFn/index.ts(27,10): \x1B[39merror TS2352: Conversion of type 'DebouncedFunc<T>' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.\n" +
    "  'DebouncedFunc<T>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Fn'.\n" +
    'TypeScript: \x1B[35m2\x1B[39m semantic errors\n' +
    'TypeScript: emit \x1B[36msucceeded\x1B[39m (with errors)\n',
  stderr: "[11:36:33] 'cjs' errored after 4.48 s\n" +
    '[11:36:33] Error: TypeScript: Compilation failed\n' +
    '    at Output.mightFinish (/Users/qiongxin/Downloads/hooks-master/node_modules/_gulp-typescript@6.0.0-alpha.1@gulp-typescript/release/output.js:131:43)\n' +
    '    at /Users/qiongxin/Downloads/hooks-master/node_modules/_gulp-typescript@6.0.0-alpha.1@gulp-typescript/release/output.js:44:22\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    "[11:36:33] 'default' errored after 4.49 s\n" +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! errno 1\n' +
    'npm ERR! ahooks@2.7.1 build: `gulp && webpack-cli`\n' +
    'npm ERR! Exit status 1\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the ahooks@2.7.1 build script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/qiongxin/.npm/_logs/2020-10-26T03_36_33_758Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run build',
  timedOut: false,
  exitCode: 1
}
```

**Comment by linbudu599** [comment]
> 要不你试试 `as unknow as T` ？如果没有报错的话，可以来个 PR。

这个应该能解决， 但似乎不太好？我觉得 #690 这个问题应该有其他的解决方式，能否提供下复现？

**Comment by brickspert** [comment]
> #690

#690 的问题是稳定复现的，因为 lodash 没有导出 Cancelable。

另外就是你报的构建问题，我这边是复现不出来的，是不是 ts 版本问题~

**Comment by awmleer** [comment]
@linbudu599 你是用 npm 安装的依赖么，我本地是正常的，可能是我们的环境不完全一样。。npm install 一下再试试？因为有 `package-lock.json` 可以尽可能确保我们环境一致

**Comment by linbudu599** [comment]
done  npm是正常的  tnpm 和 cnpm 不行...
